openapi: 3.0.0
info:
  version: 1.PreR15.1.0
  title: Namf_EventExposure Service
  description: AMF Event Exposure Service
security:
  - oAuth2ClientCredentials: []
  - {}
externalDocs:
  description: Documentation
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.518/'
servers:
  - url: '{apiRoot}/namf-evts/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in subclause subclause 4.4 of 3GPP TS 29.501
paths:
  /subscriptions:
    post:
      summary: Namf_EventExposure Subscribe service Operation
      tags:
        - Create Subscription
      operationId: CreateSubscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmfCreateEventSubscription'
        required: true
      responses:
        '201':
          description: Subsription Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmfCreatedEventSubscription'
        '400':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/400'
        '403':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/403'
        '411':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/415'
        '500':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
      callbacks:
        onEventReport:
          '{$request.body#/subscription/notifyUri}':
            post:
              summary: Event Notificaiton Delivery
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/AmfEventNotification'
                required: true
              responses:
                '204':
                  description: Successful acknowledgement
                '400':
                  $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/400'
                '411':
                  $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/415'
                '500':
                  $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/503'
                default:
                  description: Unexpected error
  /subscriptions/{subscriptionId}:
    patch:
      summary: Namf_EventExposure Subscribe Modify service Operation
      tags:
        - Modify Subscription
      operationId: ModifySubscription
      parameters:
        - name: subscriptionId
          in: path
          required: true
          description: Unique ID of the subscription to be modified
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/AmfUpdateEventSubscriptionItem'
        required: true
      responses:
        '200':
          description: Subsription modified successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmfUpdatedEventSubscription'
        '400':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/400'
        '403':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/415'
        '500':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
    delete:
      summary: Namf_EventExposure Unsubscribe service Operation
      tags:
        - Delete Subscription
      operationId: DeleteSubscription
      parameters:
        - name: subscriptionId
          in: path
          required: true
          description: Unique ID of the subscription to be deleted
          schema:
            type: string
      responses:
        '200':
          description: Subsription deleted successfully
        '400':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/415'
        '500':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes: {}
  schemas:
    AmfEventSubscription:
      type: object
      properties:
        eventList:
          type: array
          items:
            $ref: '#/components/schemas/AmfEvent'
          minItems: 1
        eventNotifyUri:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Uri'
        notifyCorrelationId:
          type: string
        nfId:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/NfInstanceId'
        subsChangeNotifyUri:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Uri'
        subsChangeNotifyCorrelationId:
          type: string
        supi:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Supi'
        groupId:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/GroupId'
        gpsi:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Gpsi'
        pei:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Pei'
        anyUE:
          type: boolean
        options:
          $ref: '#/components/schemas/AmfEventMode'
      required:
        - events
        - eventNotifyUri
        - notifyCorrelationId
        - nfId
    AmfEvent:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/AmfEventType'
        immediateFlag:
          type: boolean
        areaList:
          type: array
          items:
            $ref: '#/components/schemas/AmfEventArea'
          minItems: 0
        locationFilterList:
          type: array
          items:
            $ref: '#/components/schemas/LocationFilter'
          minItems: 0
        subscribedDataFilterList:
          type: array
          items:
            $ref: '#/components/schemas/SubscribedDataFilter'
          minItems: 0
      required:
        - type
    AmfEventNotification:
      type: object
      properties:
        subscriptionId:
          type: string
        notifyCorrelationId:
          type: string
        reportList:
          type: array
          items:
            $ref: '#/components/schemas/AmfEventReport'
          minItems: 1
      required:
        - subscriptionId
        - notifyCorrelationId
    AmfEventReport:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/AmfEventType'
        state:
          $ref: '#/components/schemas/AmfEventState'
        timeStamp:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/DateTime'
        anyUe:
          type: boolean
        supi:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Supi'
        areaList:
          type: array
          items:
            $ref: '#/components/schemas/AmfEventArea'
          minItems: 0
        gpsi:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Gpsi'
        pei:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Pei'
        location:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/UserLocation'
        timezone:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/TimeZone'
        accessTypeList:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/AccessType'
          minItems: 0
        rmInfoList:
          type: array
          items:
            $ref: '#/components/schemas/RmInfo'
          minItems: 0
        cmInfoList:
          type: array
          items:
            $ref: '#/components/schemas/CmInfo'
          minItems: 0
        reachability:
          $ref: '#/components/schemas/UeReachability'
        subscribedData:
          $ref: '#/components/schemas/SubscribedData'
        commFailure:
          $ref: '#/components/schemas/CommunicationFailure'
        numberOfUes:
          type: integer
      required:
        - type
        - state
        - timeStamp
    AmfEventMode:
      type: object
      properties:
        trigger:
          $ref: '#/components/schemas/AmfEventTrigger'
        maxReports:
          type: integer
        expiry:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/DateTime'
      required:
        - trigger
    AmfEventState:
      type: object
      properties:
        active:
          type: boolean
        remainReports:
          type: integer
        remainDuration:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/DurationSec'
      required:
        - active
    RmInfo:
      type: object
      properties:
        rmState:
          $ref: '#/components/schemas/RmState'
        accessType:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/AccessType'
      required:
        - rmState
        - accessType
    CmInfo:
      type: object
      properties:
        cmState:
          $ref: '#/components/schemas/CmState'
        accessType:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/AccessType'
      required:
        - cmState
        - accessType
    SubscribedData:
      type: object
      properties:
        sari:
          $ref: '#/components/schemas/Sari'
        rfspIndex:
          $ref: '#/components/schemas/RfspIndex'
    CommunicationFailure:
      type: object
      properties:
        nasReleaseCode:
          type: string
        ranReleaseCode:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/NgApCause'
    AmfCreateEventSubscription:
      type: object
      properties:
        subscription:
          $ref: '#/components/schemas/AmfEventSubscription'
        supportedFeatures:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - subscription
    AmfCreatedEventSubscription:
      type: object
      properties:
        subscription:
          $ref: '#/components/schemas/AmfEventSubscription'
        reportList:
          type: array
          items:
            $ref: '#/components/schemas/AmfEventReport'
          minItems: 0
        supportedFeatures:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - subscription
    AmfUpdateEventSubscriptionItem:
      type: array
      items:
        type: object
        properties:
          op:
            type: string
            enum:
              - add
              - remove
              - replace
          path:
            type: string
            pattern: '\/events\/[0-]$|\/events\/[1-9][0-9]*$'
          value:
            $ref: '#/components/schemas/AmfEvent'
        required:
          - op
          - path
      minItems: 1
    AmfUpdatedEventSubscription:
      type: object
      properties:
        subscription:
          $ref: '#/components/schemas/AmfEventSubscription'
      required:
        - subscription
    AmfEventArea:
      type: object
      properties:
        presenceInfo:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/PresenceInfo'
        ladnInfo:
          $ref: '#/components/schemas/LadnInfo'
    LadnInfo:
      type: object
      properties:
        ladn:
          type: string
        presence:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/PresenceState'
      required:
        - ladn
    5gGuti:
      type: string
    Sari:
      $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Bytes'
    RfspIndex:
      type: integer
    AmfEventType:
      anyOf:
      - type: string
        enum:
          - "LOCATION_REPORT"
          - "PRESENCE_IN_AOI_REPORT"
          - "TIMEZONE_REPORT"
          - "ACCESS_TYPE_REPORT"
          - "REGISTRATION_STATE_REPORT"
          - "CONNECTIVITY_STATE_REPORT"
          - "REACHABILITY_REPORT"
          - "SUBSCRIBED_DATA_REPORT"
          - "COMMIUNICATION_FAILURE_REPORT"
          - "UES_IN_AREA_REPORT"
      - type: string
    AmfEventTrigger:
      anyOf:
      - type: string
        enum:
          - "ONE_TIME"
          - "CONTINUOUS"
      - type: string
    LocationFilter :
      anyOf:
      - type: string
        enum:
          - "TAI"
          - "CELL_ID"
          - "N3IWF"
          - "UE_IP"
          - "UDP_PORT"
      - type: string
    SubscribedDataFilter:
      anyOf:
      - type: string
        enum:
          - "SARI"
          - "RFSP_INDEX"
      - type: string
    UeReachability:
      anyOf:
      - type: string
        enum:
          - "UNREACHABLE"
          - "REACHABLE"
          - "REGULATORY_ONLY"
      - type: string
    RmState:
      anyOf:
      - type: string
        enum:
          - "REGISTERED"
          - "DEREGISTERED"
      - type: string
    CmState:
      anyOf:
      - type: string
        enum:
          - "IDLE"
          - "CONNECTED"
      - type: string
