openapi: 3.0.0

info:
  version: '1.PreR15.1.0'
  title: 'NSSF NS Selection'
  description: 'NSSF Network Slice Selection Service'
security:
  - {}
  - oAuth2Clientcredentials: []
servers:
  - url: '{apiRoot}/nnssf-nsselection/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501
paths:
  /network-slice-information:
    get:
      summary:  Retrieve the Network Slice Selection Information 
      tags:
        - Network Slice Information (Document)
      operationId: NSSelectionGet
      parameters:
        - name: nf-type
          in: query
          description: NF type of the NF service consumer
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29510_Nnrf_NFManagement.yaml#/components/schemas/NFType'
        - name: nf-id
          in: query
          description: NF Instance ID of the NF service consumer
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/NfInstanceId'
        - name: slice-info-request-for-registration
          in: query
          description: Requested network slice information during Registration procedure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SliceInfoForRegistration'
        - name: slice-info-request-for-pdu-session
          in: query
          description: Requested network slice information during PDU session establishment procedure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SliceInfoForPDUSession'
        - name: home-plmn-id
          in: query
          description: PLMN ID of the HPLMN
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/PlmnId'
        - name: tai
          in: query
          description: TAI of the UE
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Tai'
        - name: supported-features
          in: query
          description: Features required to be supported by the NFs in the target slice instance
          schema:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
              
      responses:
        '200':
          description: OK (Successful Network Slice Selection)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizedNetworkSliceInfo'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        default:
          description: Unexpected error

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes: {}
  schemas:
    AuthorizedNetworkSliceInfo:
      type: object
      properties:
        allowedNssaiList:
          type: array
          items:
            $ref: '#/components/schemas/AllowedNssai'
          minItems: 0
        configuredNssai:
          type: array
          items:
            $ref: '#/components/schemas/ConfiguredSnssai'
        targetAmfSet:
          type: string
        candidateAmfList:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/NfInstanceId'
        rejectedNssaiInPlmn:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
        rejectedNssaiInTa:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
        nsiInformation:
          $ref: '#/components/schemas/NsiInformation'
        supportedFeatures:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        nrfAmfSet:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Uri'
      
    SubscribedSnssai:
      type: object
      required:
        - subscribedSnssai
      properties:
        subscribedSnssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
        defaultIndication:
          type: boolean
      
    
    AllowedSnssai:
      type: object
      required:
        - allowedSnssai
      properties:
        allowedSnssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
        nsiInformationList:
          type: array
          items:
            $ref: '#/components/schemas/NsiInformation'
        mappedHomeSnssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
    
    AllowedNssai:
      type: object
      required:
        - allowedSnssaiList
        - accessType
      properties:
        allowedSnssaiList:
          type: array
          items:
            $ref: '#/components/schemas/AllowedSnssai'
          minItems: 1
    
    NsiInformation:
      type: object
      required:
        - nrfId
      properties:
        nrfId:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Uri'
        nsiId:
          $ref: '#/components/schemas/NsiId'
    
    MappingOfRequestedSnssai:
      type: object
      required:
        - servingSnssai
        - homeSnssai
      properties:
        servingSnssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
        homeSnssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
    
    
    SliceInfoForRegistration:
      type: object
      properties:
        subscribedNssai:
          type: array
          items:
            $ref: '#/components/schemas/SubscribedSnssai'
        allowedNssai:
          $ref: '#/components/schemas/AllowedNssai'
        sNssaiForMapping:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
          minItems: 0
        requestedNssai:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
          minItems: 0
        mappingOfRequestedNssai:
          type: array
          items:
            $ref: '#/components/schemas/MappingOfRequestedSnssai'
        requestMapping:
          type: boolean
    
    SliceInfoForPDUSession:
      type: object
      required:
        - sNssai
        - roamingIndication
      properties:
        sNssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
        roamingIndication:
          $ref: '#/components/schemas/RoamingIndication'
        homeSnssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
    
    ConfiguredSnssai:
      type: object
      required:
        - configuredSnssai
      properties:
        configuredSnssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
        mappedHomeSnssai:
          $ref: 'https://raw.githubusercontent.com/jdegre/5GC_APIs/f10/TS29571_CommonData.yaml#/components/schemas/Snssai'
    
    
    RoamingIndication:
      anyOf:
        - type: string
          enum:
            - NON_ROAMING
            - LOCAL_BREAKOUT
            - HOME_ROUTED_ROAMING
        - type: string
    NsiId:
      type: string
